services:
  postgres:
    image: postgres:16
    container_name: metizo-postgres
    environment:
      POSTGRES_DB: metizo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - metizo_pgdata:/var/lib/postgresql/data

volumes:
  metizo_pgdata:
